### PR TITLE
Update for PR #235

### PR DESCRIPTION
**Pull request by Dummerle**
I resolved all conflicts for the old Pull Request. 
Merging this pr would be very nice, because for Rare , i have to use a submodule with the changes, to get download progress. It would be a better interaction with other GUIs too.

### CODE REVIEW

**Comment by derrod** [comment]
This seems to contain some unrealted changes, and also does other things that are bad, like creating the interactive input for SDL from the core. There will be big changes to how downloading works in the near future.

**Comment by loathingKernel** [comment]
That's fair. Can you give us a sneak peak into what changes will there be, in order to know what to expect and prepare accordingly?

As a side-note, would you be willing to accept a fixed PR?

**Comment by derrod** [comment]
Some of the big changes will be that analysis will be broken up into its own thing, there will be a new primary downloader based on asyncio, the options for downloading and such will be dataclasses instead of a huge list of parameters. That are the main ones on a high level.

At this point I don't think this PR could be rewritten in any way that would make sense to merge.

**Comment by loathingKernel** [comment]
Thank you for the explanation, very much appreciated.

**Pull request closed without merging**
