### PR TITLE
[core] Try all manifest URLs until one works

### PR DESCRIPTION
**Pull request by CommandMC**
Let's see if this stops working in a few hours

### CODE REVIEW

**Comment by nutterthanos** [comment]
It seems epic broke something or changed something with how authentication to download manifests

**Comment by mark-delchev** [comment]
Is it working now because I got the same error after installing it from PyPI?

**Comment by mark-delchev** [comment]
I just forked the repo and made the same changes. I think it works. I got this code
```
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Rocket League®" (Sugar)...
[Core] WARNING: Unable to download manifest from https://download.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default/CwPvYF6of9gkCbfGUkC7KqquxYMG-A.manifest?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IiovQnVpbGRzL09yZy9vLTk4bGFyY3R4eWhuNTVrcWpxNXhqYjl3empsOWhmOS9lNmJjY2E1YjM3ZDA0NTdjYTg4MWFlYzUwODIwNTU0Mi9kZWZhdWx0L0N3UHZZRjZvZjlna0NiZkdVa0M3S3FxdXhZTUctQS5tYW5pZmVzdCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY2MjczMjExNH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=bt46WCME1A4dR1qWEzv9DU2xpHM5A-rEYxS3Bn3xF6E5vk7E7ZVetZm4un8yCw6ZlHE0R9NwIZuxOH-w-g1Txd3yrLrFCsY6GJbFD4-AvBJvQw5hiX~QsQFYK7HQL5TFr-lag~K~FJwadbJB2d4ln5T2TgL2kbqFFz8ae1ZVwkfcgH8N2d10bvfSkuwU67VkGgOsmGc2KooLXa1cTxpIcSHKtlOwXb6D0hl5iONI-DEXP~Avzbkw0~C1Ff7GYNyz3Id0vo7P~LNI~mlMrPhhPp4sEImcPE11DTk6OJqa7FZljAkgGLIJr3Xm2eOUUO1bdNU1LHH0TgjjNQZHIb2cjA__&Key-Pair-Id=APKAJP7WU44FM4EHJYFQ, trying next one ...
[Core] WARNING: Unable to download manifest from https://download2.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default/CwPvYF6of9gkCbfGUkC7KqquxYMG-A.manifest?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IiovQnVpbGRzL09yZy9vLTk4bGFyY3R4eWhuNTVrcWpxNXhqYjl3empsOWhmOS9lNmJjY2E1YjM3ZDA0NTdjYTg4MWFlYzUwODIwNTU0Mi9kZWZhdWx0L0N3UHZZRjZvZjlna0NiZkdVa0M3S3FxdXhZTUctQS5tYW5pZmVzdCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY2MjczMjExNH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=bt46WCME1A4dR1qWEzv9DU2xpHM5A-rEYxS3Bn3xF6E5vk7E7ZVetZm4un8yCw6ZlHE0R9NwIZuxOH-w-g1Txd3yrLrFCsY6GJbFD4-AvBJvQw5hiX~QsQFYK7HQL5TFr-lag~K~FJwadbJB2d4ln5T2TgL2kbqFFz8ae1ZVwkfcgH8N2d10bvfSkuwU67VkGgOsmGc2KooLXa1cTxpIcSHKtlOwXb6D0hl5iONI-DEXP~Avzbkw0~C1Ff7GYNyz3Id0vo7P~LNI~mlMrPhhPp4sEImcPE11DTk6OJqa7FZljAkgGLIJr3Xm2eOUUO1bdNU1LHH0TgjjNQZHIb2cjA__&Key-Pair-Id=APKAJP7WU44FM4EHJYFQ, trying next one ...
[Core] WARNING: Unable to download manifest from https://download3.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default/CwPvYF6of9gkCbfGUkC7KqquxYMG-A.manifest?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IiovQnVpbGRzL09yZy9vLTk4bGFyY3R4eWhuNTVrcWpxNXhqYjl3empsOWhmOS9lNmJjY2E1YjM3ZDA0NTdjYTg4MWFlYzUwODIwNTU0Mi9kZWZhdWx0L0N3UHZZRjZvZjlna0NiZkdVa0M3S3FxdXhZTUctQS5tYW5pZmVzdCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY2MjczMjExNH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=bt46WCME1A4dR1qWEzv9DU2xpHM5A-rEYxS3Bn3xF6E5vk7E7ZVetZm4un8yCw6ZlHE0R9NwIZuxOH-w-g1Txd3yrLrFCsY6GJbFD4-AvBJvQw5hiX~QsQFYK7HQL5TFr-lag~K~FJwadbJB2d4ln5T2TgL2kbqFFz8ae1ZVwkfcgH8N2d10bvfSkuwU67VkGgOsmGc2KooLXa1cTxpIcSHKtlOwXb6D0hl5iONI-DEXP~Avzbkw0~C1Ff7GYNyz3Id0vo7P~LNI~mlMrPhhPp4sEImcPE11DTk6OJqa7FZljAkgGLIJr3Xm2eOUUO1bdNU1LHH0TgjjNQZHIb2cjA__&Key-Pair-Id=APKAJP7WU44FM4EHJYFQ, trying next one ...
[Core] WARNING: Unable to download manifest from https://download4.epicgames.com/Builds/Org/o-98larctxyhn55kqjq5xjb9wzjl9hf9/e6bcca5b37d0457ca881aec508205542/default/CwPvYF6of9gkCbfGUkC7KqquxYMG-A.manifest?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6IiovQnVpbGRzL09yZy9vLTk4bGFyY3R4eWhuNTVrcWpxNXhqYjl3empsOWhmOS9lNmJjY2E1YjM3ZDA0NTdjYTg4MWFlYzUwODIwNTU0Mi9kZWZhdWx0L0N3UHZZRjZvZjlna0NiZkdVa0M3S3FxdXhZTUctQS5tYW5pZmVzdCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY2MjczMjExNH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=bt46WCME1A4dR1qWEzv9DU2xpHM5A-rEYxS3Bn3xF6E5vk7E7ZVetZm4un8yCw6ZlHE0R9NwIZuxOH-w-g1Txd3yrLrFCsY6GJbFD4-AvBJvQw5hiX~QsQFYK7HQL5TFr-lag~K~FJwadbJB2d4ln5T2TgL2kbqFFz8ae1ZVwkfcgH8N2d10bvfSkuwU67VkGgOsmGc2KooLXa1cTxpIcSHKtlOwXb6D0hl5iONI-DEXP~Avzbkw0~C1Ff7GYNyz3Id0vo7P~LNI~mlMrPhhPp4sEImcPE11DTk6OJqa7FZljAkgGLIJr3Xm2eOUUO1bdNU1LHH0TgjjNQZHIb2cjA__&Key-Pair-Id=APKAJP7WU44FM4EHJYFQ, trying next one ...
[Core] INFO: Parsing game manifest...
[Core] INFO: Install path: /home/mark/Games/rocketleague
[Core] INFO: Selected CDN: download.epicgames.com (https)
[cli] INFO: Install size: 23790.42 MiB
[cli] INFO: Download size: 20494.86 MiB (Compression savings: 2.0%)
[cli] INFO: Reusable size: 0.00 MiB (chunks) / 0.00 MiB (unchanged / skipped)
[cli] INFO: Downloads are resumable, you can interrupt the download with CTRL-C and resume it using the same command later on.

This game may have compatibility issues or require additional setup, see: https://github.com/CommandMC/EpicLinux/wiki/Rocket-League:-BakkesMod

```

**Comment by Nomad404** [comment]
@derrod any ETA on this merge?

**Comment by guihkx** [comment]
For desperate people (like myself), you can download a legendary build containing this fix [from here](https://github.com/derrod/legendary/actions/runs/3014652272).

**Comment by derrod** [comment]
> @derrod any ETA on this merge?

Sometime next week. Probably.

**Comment by kekonn** [comment]
> For desperate people (like myself), you can download a legendary build containing this fix [from here](https://github.com/derrod/legendary/actions/runs/3014652272).

For the desperate and clueless: download the package for your platform from the above link, unzip it, make it executable (usually a checkbox in the properties window of the file), then open Heroic and in the settings, go to Advanced and there you can select an alternative legendary binary. Point it to the one you just downloaded and presto!

**Comment by Nomad404** [comment]
> > For desperate people (like myself), you can download a legendary build containing this fix [from here](https://github.com/derrod/legendary/actions/runs/3014652272).
> 
> For the desperate and clueless: download the package for your platform from the above link, unzip it, make it executable (usually a checkbox in the properties window of the file), then open Heroic and in the settings, go to Advanced and there you can select an alternative legendary binary. Point it to the one you just downloaded and presto!
> 

Thanks for the tip, I've just replaced the binary in the app folder 😅

**Comment by derrod** [comment]
I updated it a bit to not log the full URL and log the last error if all fail. I still can't make a full release from where I am right now but I'll try to do so as soon as possible.

**Pull request merged**
